### Goal: predict a dog's lifespan using keras


In [1]:
import keras as kr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
df = pd.read_csv("datasets/dogs.csv")

In [3]:
df.head()

pure  age  weight  height  lifespan
0   True    3    7.94    49.6        15
1   True    7    5.05    63.5        17
2   True    6   16.15    68.2        11
3  False    3   15.50    64.7        12
4  False    3   12.17    59.7        14

In [4]:
# pure needs to be in number form, it has two categories which we can represent as 1 and 0
df['ispure'] =(df['pure'] == True).astype(np.int)
df['isnotpure'] = (df['pure'] == False).astype(np.int)
df

pure  age  weight  height  lifespan  ispure  isnotpure
0    True    3    7.94    49.6        15       1          0
1    True    7    5.05    63.5        17       1          0
2    True    6   16.15    68.2        11       1          0
3   False    3   15.50    64.7        12       0          1
4   False    3   12.17    59.7        14       0          1
..    ...  ...     ...     ...       ...     ...        ...
95  False    4   20.76    52.2        10       0          1
96  False    4   17.40    47.5        11       0          1
97  False    6   15.60    51.4        12       0          1
98  False    3    8.37    54.1        16       0          1
99   True    7    9.09    50.3        14       1          0

[100 rows x 7 columns]

In [5]:
inputs = df[['age', 'weight', 'height', 'ispure', 'isnotpure']]
inputs

age  weight  height  ispure  isnotpure
0     3    7.94    49.6       1          0
1     7    5.05    63.5       1          0
2     6   16.15    68.2       1          0
3     3   15.50    64.7       0          1
4     3   12.17    59.7       0          1
..  ...     ...     ...     ...        ...
95    4   20.76    52.2       0          1
96    4   17.40    47.5       0          1
97    6   15.60    51.4       0          1
98    3    8.37    54.1       0          1
99    7    9.09    50.3       1          0

[100 rows x 5 columns]

In [6]:
output = df['lifespan']
output

0     15
1     17
2     11
3     12
4     14
      ..
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [7]:
# Create a new neural network.
m = kr.models.Sequential()

In [8]:
# Add neurons.
# input dim = number of inputs
m.add(kr.layers.Dense(10, input_dim=5, activation="linear"))
m.add(kr.layers.Dense(30, activation="sigmoid"))
m.add(kr.layers.Dense(10, activation="linear"))
m.add(kr.layers.Dense(10, activation="linear"))
#how many outputs?
m.add(kr.layers.Dense(1, activation='linear'))

# Compile the model.
m.compile(loss="mean_squared_error", optimizer="adam")

In [9]:
# Train the model.
#m.fit(x, y, epochs=30, batch_size=10)
# Train the model.
m.fit(inputs, output, epochs=30, batch_size=10)

Epoch 1/30
100/100 [==============================] - 2s 16ms/step - loss: 161.2301
Epoch 2/30
100/100 [==============================] - 0s 472us/step - loss: 136.9557
Epoch 3/30
100/100 [==============================] - 0s 506us/step - loss: 116.8980
Epoch 4/30
100/100 [==============================] - 0s 459us/step - loss: 97.7804
Epoch 5/30
100/100 [==============================] - 0s 448us/step - loss: 78.7767
Epoch 6/30
100/100 [==============================] - 0s 515us/step - loss: 57.1157
Epoch 7/30
100/100 [==============================] - 0s 422us/step - loss: 35.4692
Epoch 8/30
100/100 [==============================] - 0s 400us/step - loss: 19.4750
Epoch 9/30
100/100 [==============================] - 0s 389us/step - loss: 10.3359
Epoch 10/30
100/100 [==============================] - 0s 354us/step - loss: 6.8489
Epoch 11/30
100/100 [==============================] - 0s 424us/step - loss: 6.0371
Epoch 12/30
100/100 [==============================] - 0s 424us/step - los

In [10]:
m.predict(inputs)

array([[14.656704 ],
       [15.50997  ],
       [12.854504 ],
       [13.067181 ],
       [14.123203 ],
       [10.872667 ],
       [14.096693 ],
       [11.508738 ],
       [12.49553  ],
       [11.139748 ],
       [12.072212 ],
       [15.434155 ],
       [10.893358 ],
       [14.289583 ],
       [11.8361225],
       [12.46642  ],
       [14.473355 ],
       [11.520792 ],
       [10.952726 ],
       [11.05611  ],
       [11.171043 ],
       [11.051335 ],
       [14.143314 ],
       [11.14422  ],
       [11.549162 ],
       [13.7312355],
       [13.15967  ],
       [11.502008 ],
       [14.411267 ],
       [10.969564 ],
       [11.007578 ],
       [11.013482 ],
       [11.071908 ],
       [15.414855 ],
       [10.802841 ],
       [11.659561 ],
       [15.14487  ],
       [12.731653 ],
       [11.462846 ],
       [11.803913 ],
       [11.561444 ],
       [13.565385 ],
       [10.904856 ],
       [13.534622 ],
       [13.297699 ],
       [11.83841  ],
       [13.435844 ],
       [10.95

In [11]:
np.around(m.predict(inputs).T)

array([[15., 16., 13., 13., 14., 11., 14., 12., 12., 11., 12., 15., 11.,
        14., 12., 12., 14., 12., 11., 11., 11., 11., 14., 11., 12., 14.,
        13., 12., 14., 11., 11., 11., 11., 15., 11., 12., 15., 13., 11.,
        12., 12., 14., 11., 14., 13., 12., 13., 11., 13., 11., 14., 11.,
        11., 11., 11., 12., 11., 14., 11., 11., 11., 13., 12., 15., 13.,
        14.,  8., 12., 13., 12., 11., 15., 11., 12., 11., 15., 12., 14.,
        11., 11., 11., 13., 15., 11., 15., 14., 11., 15., 11., 11., 15.,
        14., 11., 13., 13., 11., 11., 12., 15., 14.]], dtype=float32)

In [12]:
output.as_matrix()

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([15, 17, 11, 12, 14, 12, 15, 11, 13, 10, 12, 17, 10, 14, 12, 11, 16,
       12, 11, 10, 12, 11, 15, 11, 11, 14, 15, 11, 17, 10, 10, 11, 11, 19,
        8, 13, 16, 14, 10, 12, 12, 14, 10, 13, 14, 11, 15, 10, 15, 12, 13,
       12, 10, 11, 10, 11, 10, 14, 10, 11, 11, 11, 13, 19, 14, 14,  8, 12,
       11, 11, 11, 16, 13, 12, 12, 18, 12, 16, 11,  8,  8, 12, 18,  9, 16,
       13,  9, 16,  9, 11, 16, 13,  8, 14, 15, 10, 11, 12, 16, 14])

In [13]:
# differences 
m.predict(inputs).T - output.as_matrix()

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


array([[-0.34329605, -1.49003029,  1.85450363,  1.06718063,  0.12320328,
        -1.12733269, -0.90330696,  0.50873756, -0.50446987,  1.13974762,
         0.07221222, -1.56584454,  0.89335823,  0.28958321, -0.16387749,
         1.46642017, -1.52664471, -0.47920799, -0.04727364,  1.05611038,
        -0.8289566 ,  0.05133533, -0.85668564,  0.14422035,  0.54916191,
        -0.2687645 , -1.84033012,  0.50200844, -2.58873272,  0.96956444,
         1.0075779 ,  0.01348209,  0.071908  , -3.585145  ,  2.80284119,
        -1.34043884, -0.8551302 , -1.26834679,  1.4628458 , -0.19608688,
        -0.43855572, -0.43461514,  0.90485573,  0.53462219, -0.70230103,
         0.83841038, -1.56415558,  0.95983505, -1.97264862, -0.57407379,
         0.91821861, -0.83707142,  0.88215733,  0.32018661,  1.24694824,
         0.59682655,  1.30871773, -0.01143265,  1.07338142, -0.03614426,
        -0.03970718,  2.02072906, -0.51573753, -3.80453491, -1.05832291,
         0.19847107,  0.34931755, -0.10131836,  1.8

In [14]:
# mean squared error
# see how well you neuron network is doing
np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

/usr/local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


13.394486853939673

In [ ]:
#x = inputs
#y = output

# Run each x value through the neural network.
p = m.predict(x)

# Plot the values.
plt.plot(inputs, p, 'r-', label='Prediction')
plt.plot(inputs, y, 'k:', label='Original')
plt.legend()