Tutorial on keras 
https://gist.github.com/NiharG15/cd8272c9639941cf8f481a7c4478d525

In [39]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [44]:

iris_data = load_iris() # load the iris dataset

In [41]:
print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [45]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

In [46]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

//anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [47]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)


In [48]:
# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))


In [49]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [50]:

print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [51]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)


Epoch 1/200
 - 1s - loss: 1.6805 - accuracy: 0.3417
Epoch 2/200
 - 0s - loss: 1.4631 - accuracy: 0.3417
Epoch 3/200
 - 0s - loss: 1.3309 - accuracy: 0.3417
Epoch 4/200
 - 0s - loss: 1.2380 - accuracy: 0.3417
Epoch 5/200
 - 0s - loss: 1.1519 - accuracy: 0.2000
Epoch 6/200
 - 0s - loss: 1.0683 - accuracy: 0.2333
Epoch 7/200
 - 0s - loss: 0.9801 - accuracy: 0.6500
Epoch 8/200
 - 0s - loss: 0.8989 - accuracy: 0.7917
Epoch 9/200
 - 0s - loss: 0.8310 - accuracy: 0.8667
Epoch 10/200
 - 0s - loss: 0.7687 - accuracy: 0.8500
Epoch 11/200
 - 0s - loss: 0.7107 - accuracy: 0.8333
Epoch 12/200
 - 0s - loss: 0.6607 - accuracy: 0.8417
Epoch 13/200
 - 0s - loss: 0.6136 - accuracy: 0.8417
Epoch 14/200
 - 0s - loss: 0.5732 - accuracy: 0.8500
Epoch 15/200
 - 0s - loss: 0.5361 - accuracy: 0.8750
Epoch 16/200
 - 0s - loss: 0.5051 - accuracy: 0.8833
Epoch 17/200
 - 0s - loss: 0.4754 - accuracy: 0.9167
Epoch 18/200
 - 0s - loss: 0.4488 - accuracy: 0.9250
Epoch 19/200
 - 0s - loss: 0.4264 - accuracy: 0.9500
E

 - 0s - loss: 0.0535 - accuracy: 0.9833
Epoch 152/200
 - 0s - loss: 0.0588 - accuracy: 0.9750
Epoch 153/200
 - 0s - loss: 0.0442 - accuracy: 0.9833
Epoch 154/200
 - 0s - loss: 0.0476 - accuracy: 0.9917
Epoch 155/200
 - 0s - loss: 0.0460 - accuracy: 0.9917
Epoch 156/200
 - 0s - loss: 0.0463 - accuracy: 0.9917
Epoch 157/200
 - 0s - loss: 0.0492 - accuracy: 0.9750
Epoch 158/200
 - 0s - loss: 0.0465 - accuracy: 0.9833
Epoch 159/200
 - 0s - loss: 0.0525 - accuracy: 0.9750
Epoch 160/200
 - 0s - loss: 0.0500 - accuracy: 0.9750
Epoch 161/200
 - 0s - loss: 0.0458 - accuracy: 0.9833
Epoch 162/200
 - 0s - loss: 0.0441 - accuracy: 0.9833
Epoch 163/200
 - 0s - loss: 0.0422 - accuracy: 0.9917
Epoch 164/200
 - 0s - loss: 0.0469 - accuracy: 0.9917
Epoch 165/200
 - 0s - loss: 0.0421 - accuracy: 0.9917
Epoch 166/200
 - 0s - loss: 0.0416 - accuracy: 0.9917
Epoch 167/200
 - 0s - loss: 0.0412 - accuracy: 0.9917
Epoch 168/200
 - 0s - loss: 0.0418 - accuracy: 0.9917
Epoch 169/200
 - 0s - loss: 0.0410 - accur

In [52]:
# Test on unseen data

results = model.evaluate(test_x, test_y)

30/30 [==============================] - 0s 3ms/step


In [53]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.151927
Final test set accuracy: 0.966667
